### ISSUE TITLE
A lock file already exists

### ISSUE THREAD

**Issue by morganhowarth-fd** [percona/pxc_scheduler_handler#50]
Hi,

We've recently implemented this tool across 2 separate hardware deployments and multiple virtual machines. All environments log the same issue in Datadog sporadically:

```
A lock file named: /var/lib/proxysql/pxc_scheduler_lock/10_HG_100_W_HG_101_R  already exists.
If this is a refuse of a dirty execution remove it manually to have the check able to run
CheckTimeout exceeded try to increase it above the execution time : 4253
```

I don't think this would be an issue with the backend servers because application servers that connect to the same backend log these messages completely randomly. For example if it were a network problem I'd expect all hosts to log at the same time?

I will set their logging to debug for a while and try and capture more info.

Config:
```
[pxccluster]
activeFailover = 1
failBack = true
checkTimeOut = 4000
mainSegment = 0
hgW = 100
hgR = 101
configHgRange = 8000
maintenanceHgRange = 9000
singlePrimary = true
maxNumWriters = 1
writerIsAlsoReader = 1
retryUp = 0
retryDown = 2
clusterId = 10
persistPrimarySettings = 0

[proxysql]
port = 6032
host = "127.0.0.1"
user = "###"
password = "###"
clustered = false
lockfilepath = "/var/lib/proxysql/pxc_scheduler_lock"
respectManualOfflineSoft = false

[global]
logLevel = "warning"
logTarget = "file"
logFile = "/var/log/pxc_scheduler_handler/pscheduler.log"
daemonize = false
daemonInterval = 2000
performance = false
OS = "na"
lockfiletimeout = 60
lockclustertimeout = 600
```

**Comment by morganhowarth-fd** [comment]
Caught another instance of the log entry with debug enabled:

```
[INFO]:2022-01-20 02:24:34 - Go version: go1.16.13
[DEBUG]:2022-01-20 02:24:34 - Testing the log
[INFO]:2022-01-20 02:24:34 - Testing the log
[WARNING]:2022-01-20 02:24:34 - Testing the log
[ERROR]:2022-01-20 02:24:34 - testing log errors
[DEBUG]:2022-01-20 02:24:34 - Log initialized
[INFO]:2022-01-20 02:24:34 - LockerImpl initialized
[ERROR]:2022-01-20 02:24:34 - A lock file named: /var/lib/proxysql/pxc_scheduler_lock/10_HG_100_W_HG_101_R  already exists.
```

Whenever this happens we also see that the CheckTimeout fails on the next run:

```
[INFO]:2022-01-20 02:24:36 - Go version: go1.16.13
[DEBUG]:2022-01-20 02:24:36 - Testing the log
[INFO]:2022-01-20 02:24:36 - Testing the log
[WARNING]:2022-01-20 02:24:36 - Testing the log
[ERROR]:2022-01-20 02:24:36 - testing log errors
[DEBUG]:2022-01-20 02:24:36 - Log initialized
[INFO]:2022-01-20 02:24:36 - LockerImpl initialized
[ERROR]:2022-01-20 02:24:36 - A lock file named: /var/lib/proxysql/pxc_scheduler_lock/10_HG_100_W_HG_101_R  already exists.
[DEBUG]:2022-01-20 02:24:36 - time taken :4260 checkTimeOut : 4000
[ERROR]:2022-01-20 02:24:36 - CheckTimeout exceeded try to increase it above the execution time : 4260
[DEBUG]:2022-01-20 02:24:36 - PXC cluster data nodes initialized
[DEBUG]:2022-01-20 02:24:36 - Evaluating node 101_db1:3306
[DEBUG]:2022-01-20 02:24:36 - Evaluating node 100_db3:3306
[DEBUG]:2022-01-20 02:24:36 - Evaluating node 101_db3:3306
[DEBUG]:2022-01-20 02:24:36 - Evaluating node 101_db2:3306
[INFO]:2022-01-20 02:24:36 - Processing action node list and build SQL commands
[INFO]:2022-01-20 02:24:36 - Connection close
[INFO]:2022-01-20 02:24:36
```

I still think that this locking issue is causing the CheckTimeout to fail as we have no evidence to suggest otherwise.

**Comment by Tusamarco** [comment]
@morganhowarth-fd  no need to investigate I know very well why this message is raised (see also https://github.com/percona/pxc_scheduler_handler/issues/39).
In short, when the pxc_scheduler is run inside ProxySQL scheduler, it create a lock file to avoid to have duplicated process running at the same time. This may happen IF an operation remain pending for a time that is longer than the interval defined for the execution. 
Normally the file is removed without problem at the end of the execution.

Given that there are two possible reasons for that file to exists:
1. the execution time is longer than the interval
2. the pxc_schedule was killed while executing and did not removed the lock file.

Case 2 is the one I will fix with the FR-39.
However your case is is the 1, see: 
```
[ERROR]:2022-01-20 02:24:36 - A lock file named: /var/lib/proxysql/pxc_scheduler_lock/10_HG_100_W_HG_101_R  already exists.
[DEBUG]:2022-01-20 02:24:36 - time taken :4260 checkTimeOut : 4000
[ERROR]:2022-01-20 02:24:36 - CheckTimeout exceeded try to increase it above the execution time : 4260
```
for some reasons the execution time is sometimes exceeding the interval.
Now given normally the checks execute in less than 100ms the fact it exceeds the 4 seconds worries me, and tells me there is something wrong somewhere in collecting the data from the cluster. 
Can you please
- activate debug and `performance` to get time stats about each phase
- let me have the log when the issue occurs

thanks

**Comment by Tusamarco** [comment]
If you use as daemon then you need to disable the one in the scheduler and run it as systemd service. I would say we should focus on WHy is taking longer sometimes first.
@morganhowarth-fd

**Comment by morganhowarth-fd** [comment]
@Tusamarco 

Here's a log snapshot from when the problem happens. Seems to be `data_cluster_init` taking the longest.

```
[INFO]:2022-01-20 07:32:33 - Go version: go1.16.13
[DEBUG]:2022-01-20 07:32:33 - Testing the log
[INFO]:2022-01-20 07:32:33 - Testing the log
[WARNING]:2022-01-20 07:32:33 - Testing the log
[ERROR]:2022-01-20 07:32:33 - testing log errors
[DEBUG]:2022-01-20 07:32:33 - Log initialized
[INFO]:2022-01-20 07:32:33 - LockerImpl initialized
[DEBUG]:2022-01-20 07:32:33 - ProxySQL node initialized
[DEBUG]:2022-01-20 07:32:33 - Cluster arguments  clusterid=10 hg_w:100 hg_r:101 bckhg_w:8100 bckhg_w:8101 singlePrimary:true num_writers:1 writer_is_also_r:1 retry_up:0 retry_down:2 check_timeout:4000 main_segment:0
[DEBUG]:2022-01-20 07:32:33 - Retrieving information from node: db2:3306
[DEBUG]:2022-01-20 07:32:33 - Retrieving information from node: db1:3306
[DEBUG]:2022-01-20 07:32:33 - Retrieving information from node: db3:3306
[DEBUG]:2022-01-20 07:32:33 - node db3:3306 done
[DEBUG]:2022-01-20 07:32:33 - node db1:3306 done
[DEBUG]:2022-01-20 07:32:33 - node db2:3306 done
[INFO]:2022-01-20 07:32:35 - Go version: go1.16.13
[DEBUG]:2022-01-20 07:32:35 - Testing the log
[INFO]:2022-01-20 07:32:35 - Testing the log
[WARNING]:2022-01-20 07:32:35 - Testing the log
[ERROR]:2022-01-20 07:32:35 - testing log errors
[DEBUG]:2022-01-20 07:32:35 - Log initialized
[INFO]:2022-01-20 07:32:35 - LockerImpl initialized
[ERROR]:2022-01-20 07:32:35 - A lock file named: /var/lib/proxysql/pxc_scheduler_lock/10_HG_100_W_HG_101_R  already exists.
[DEBUG]:2022-01-20 07:32:37 - time taken :4263 checkTimeOut : 4000
[ERROR]:2022-01-20 07:32:37 - CheckTimeout exceeded try to increase it above the execution time : 4263
[DEBUG]:2022-01-20 07:32:37 - PXC cluster data nodes initialized
[DEBUG]:2022-01-20 07:32:37 - Evaluating node 100_db3:3306
[DEBUG]:2022-01-20 07:32:37 - Evaluating node 101_db3:3306
[DEBUG]:2022-01-20 07:32:37 - Evaluating node 101_db2:3306
[DEBUG]:2022-01-20 07:32:37 - Evaluating node 101_db1:3306
[INFO]:2022-01-20 07:32:37 - Processing action node list and build SQL commands
[INFO]:2022-01-20 07:32:37 - Connection close
[INFO]:2022-01-20 07:32:37 - ======== Reporting execution times (nanosec/ms)by phase ============
[INFO]:2022-01-20 07:32:37 - Phase: main = 4,269,351,033 us 4269 ms
[INFO]:2022-01-20 07:32:37 - Phase: proxysql_init = 1,734,158 us 1 ms
[INFO]:2022-01-20 07:32:37 - Phase: main_connection = 552,026 us 0 ms
[INFO]:2022-01-20 07:32:37 - Phase: data_cluster_init = 4,267,185,015 us 4267 ms
[INFO]:2022-01-20 07:32:37 - Phase: loadNodes = 2,979,754 us 2 ms
[INFO]:2022-01-20 07:32:37 - Phase: Get info for node db3:3306 = 3,060,272 us 3 ms
[INFO]:2022-01-20 07:32:37 - Phase: node_connection_db3:3306 = 1,083,834 us 1 ms
[INFO]:2022-01-20 07:32:37 - Phase: Get info for node db1:3306 = 3,511,481 us 3 ms
[INFO]:2022-01-20 07:32:37 - Phase: node_connection_db1:3306 = 1,079,334 us 1 ms
[INFO]:2022-01-20 07:32:37 - Phase: Get info for node db2:3306 = 3,517,487 us 3 ms
[INFO]:2022-01-20 07:32:37 - Phase: node_connection_db2:3306 = 1,119,291 us 1 ms
[INFO]:2022-01-20 07:32:37 - Phase: Get Action Map (DataClusterImpl) = 285,390 us 0 ms
[INFO]:2022-01-20 07:32:37 - Phase: Process changes - ActionMap - (ProxysqlNode) = 5,083 us 0 ms
[INFO]:2022-01-20 07:32:37
```

**Comment by Tusamarco** [comment]
@morganhowarth-fd  yes, and this could make sense. 
This is the moment when communication is opened with all data nodes (connections), to evaluate their status. If the nodes are experiencing high traffic and many open connection, then the establish of the connection itself may take a bit longer.
You can:
1. increase a bit the time interval. from 4s to 5s
2. investigate if at the time of the issue you also experience any delay/performance loss in the data node.
If 2 is true it may be a sign that some "tuning" on the cluster is needed.

**Comment by morganhowarth-fd** [comment]
@Tusamarco We did have the timeout set to 2s, then 4s, I will try increase it again.

We have multiple instances connecting to the same backend servers so I would expect all nodes to have the same issue at the same time? At the moment it's totally random. We don't see any performance issues with the DB when these logs happen.

We also always get "A lock file named: /var/lib/proxysql/pxc_scheduler_lock/10_HG_100_W_HG_101_R  already exists." logged before the check timeout. Could this be related?

**Comment by Tusamarco** [comment]
@morganhowarth-fd  do you think it would be useful if I add the process id in the log after the Log level? To identify who does what?

**Comment by Tusamarco** [comment]
@morganhowarth-fd if you compile the branch https://github.com/percona/pxc_scheduler_handler/tree/Issue-50 
I have add some more info about connection close:
```
[INFO]:2022-01-20 17:43:52 - ======== Reporting execution times (nanosec/ms)by phase ============
[INFO]:2022-01-20 17:43:52 - Phase: main = 41,871,000 us 41 ms
[INFO]:2022-01-20 17:43:52 - Phase: proxysql_init = 7,831,000 us 7 ms
[INFO]:2022-01-20 17:43:52 - Phase: main_connection = 3,689,000 us 3 ms
[INFO]:2022-01-20 17:43:52 - Phase: data_cluster_init = 33,360,000 us 33 ms
[INFO]:2022-01-20 17:43:52 - Phase: loadNodes = 6,577,000 us 6 ms
[INFO]:2022-01-20 17:43:52 - Phase: Get info for node 192.168.4.21:3306 = 22,514,000 us 22 ms
[INFO]:2022-01-20 17:43:52 - Phase: Get info for node 192.168.4.205:3306 = 25,177,000 us 25 ms
[INFO]:2022-01-20 17:43:52 - Phase: node_connection_192.168.4.21:3306 = 3,794,000 us 3 ms
[INFO]:2022-01-20 17:43:52 - Phase: node_connection_192.168.4.205:3306 = 3,924,000 us 3 ms
[INFO]:2022-01-20 17:43:52 - Phase: Get info for node 192.168.4.231:3306 = 26,006,000 us 26 ms
[INFO]:2022-01-20 17:43:52 - Phase: node_connection_192.168.4.231:3306 = 4,139,000 us 4 ms
[INFO]:2022-01-20 17:43:52 - Phase: Closing connection for node 192.168.4.21:3306 = 29,000 us 0 ms. <----
[INFO]:2022-01-20 17:43:52 - Phase: Closing connection for node 192.168.4.205:3306 = 38,000 us 0 ms <----
[INFO]:2022-01-20 17:43:52 - Phase: Closing connection for node 192.168.4.231:3306 = 40,000 us 0 ms <----
[INFO]:2022-01-20 17:43:52 - Phase: Get Action Map (DataClusterImpl) = 465,000 us 0 ms
[INFO]:2022-01-20 17:43:52 - Phase: Process changes - ActionMap - (ProxysqlNode) = 16,000 us 0 ms
```
this should help us to understand better what is going on. 
Btw I am trying to replicate the issue you are having , but so far not able to.

**Comment by morganhowarth-fd** [comment]
Hi @Tusamarco thanks for investigating and providing the test branch. I'll compile this and deploy to our dev environments to see if we can gather any more information. I'm also going to run a packet capture to see what I can find on the TCP/IP stack.

**Comment by morganhowarth-fd** [comment]
@Tusamarco I can't find anything obvious in the packet captures when we exceed the checkTimeOut.

I might raise this with Percona support to see if they can help us with debugging this and/or tune our clusters to avoid this.

**Comment by Tusamarco** [comment]
That is ok also mention you are working with me on the pxc scheduler side.
BTW can you please share the log with the connection close time? Do you 
had evidence that the connection remain pending?

thanks

------------------------------------------------
Marco Tusa,
Mobile: +1-613-282-7337
do something for your planet!
http://www.tusacentral.net/
------------------------------------------------
Save a tree... please don't print this e-mail unless you really need to

**Comment by Tusamarco** [comment]
@morganhowarth-fd can u share the log with the connection close information as well please.
BTW  I am working on FR39 so soon that event will be demoted to a `warning` which should also fix your noise problem.
However, I am still really interested to discover WHY this happens, given we did not have the issue in any other customer setup, and not able to reproduce it either.

**Comment by morganhowarth-fd** [comment]
@Tusamarco is this the log you want?

```
2022-01-22T07:36:32.249Z   Go version: go1.16.13
2022-01-22T07:36:32.249Z   LockerImpl initialized
2022-01-22T07:36:34.251Z   Go version: go1.16.13
2022-01-22T07:36:34.251Z   LockerImpl initialized
2022-01-22T07:36:34.251Z   A lock file named: /var/lib/proxysql/pxc_scheduler_lock/10_HG_100_W_HG_101_R already exists.
2022-01-22T07:36:34.251Z   If this is a refuse of a dirty execution remove it manually to have the check able to run
2022-01-22T07:36:36.253Z   Go version: go1.16.13
2022-01-22T07:36:36.253Z   LockerImpl initialized
2022-01-22T07:36:36.253Z   A lock file named: /var/lib/proxysql/pxc_scheduler_lock/10_HG_100_W_HG_101_R already exists.
2022-01-22T07:36:36.253Z   If this is a refuse of a dirty execution remove it manually to have the check able to run
2022-01-22T07:36:38.254Z   Go version: go1.16.13
2022-01-22T07:36:38.254Z   LockerImpl initialized
2022-01-22T07:36:38.254Z   A lock file named: /var/lib/proxysql/pxc_scheduler_lock/10_HG_100_W_HG_101_R already exists.
2022-01-22T07:36:38.254Z   If this is a refuse of a dirty execution remove it manually to have the check able to run
2022-01-22T07:36:40.256Z   Go version: go1.16.13
2022-01-22T07:36:40.256Z   LockerImpl initialized
2022-01-22T07:36:40.256Z   A lock file named: /var/lib/proxysql/pxc_scheduler_lock/10_HG_100_W_HG_101_R already exists.
2022-01-22T07:36:40.256Z   If this is a refuse of a dirty execution remove it manually to have the check able to run
2022-01-22T07:36:42.257Z   Go version: go1.16.13
2022-01-22T07:36:42.257Z   LockerImpl initialized
2022-01-22T07:36:42.257Z   A lock file named: /var/lib/proxysql/pxc_scheduler_lock/10_HG_100_W_HG_101_R already exists.
2022-01-22T07:36:42.257Z   If this is a refuse of a dirty execution remove it manually to have the check able to run
2022-01-22T07:36:42.257Z   CheckTimeout exceeded try to increase it above the execution time : 10655
2022-01-22T07:36:42.257Z   Processing action node list and build SQL commands
2022-01-22T07:36:42.257Z   Connection close
2022-01-22T07:36:42.257Z   '======== Reporting execution times (nanosec/ms)by phase ============
2022-01-22T07:36:42.257Z   Phase: main = 10,660,690,228 us 10660 ms
2022-01-22T07:36:42.257Z   Phase: proxysql_init = 1,717,154 us 1 ms
2022-01-22T07:36:42.257Z   Phase: main_connection = 541,969 us 0 ms
2022-01-22T07:36:42.257Z   Phase: data_cluster_init = 10,658,604,535 us 10658 ms
2022-01-22T07:36:42.257Z   Phase: loadNodes = 3,020,378 us 3 ms
2022-01-22T07:36:42.257Z   Phase: Get info for node db1:3306 = 4,010,026 us 4 ms
2022-01-22T07:36:42.257Z   Phase: node_connection_db1:3306 = 1,176,562 us 1 ms
2022-01-22T07:36:42.257Z   Phase: Get info for node db2:3306 = 4,164,669 us 4 ms
2022-01-22T07:36:42.257Z   Phase: node_connection_db2:3306 = 1,146,025 us 1 ms
2022-01-22T07:36:42.257Z   Phase: Get info for node db3:3306 = 3,347,677 us 3 ms
2022-01-22T07:36:42.257Z   Phase: node_connection_db3:3306 = 1,137,244 us 1 ms
2022-01-22T07:36:42.257Z   Phase: Closing connection for node db3:3306 = 39,259 us 0 ms
2022-01-22T07:36:42.257Z   Phase: Closing connection for node db1:3306 = 41,774 us 0 ms
2022-01-22T07:36:42.257Z   Phase: Closing connection for node db2:3306 = 39,167 us 0 ms
2022-01-22T07:36:42.257Z   Phase: Get Action Map (DataClusterImpl) = 258,465 us 0 ms
2022-01-22T07:36:42.257Z   Phase: Process changes - ActionMap - (ProxysqlNode) = 4,592 us 0 ms
```

This is the most recent log entry (22nd January) since then we have not seen a reoccurrence since then.

The packet captures I have are a bit noisy with other MySQL traffic so it's difficult to pin-point the exact connection open/close that the scheduler initiated.

Could you explain a bit more what `data_cluster_init` is doing? Where would it be establishing a connection to? All backend nodes or a random one?

**Comment by Tusamarco** [comment]
As reported in the final image in [read me](https://user-images.githubusercontent.com/5564455/151006187-f345bee4-48ce-4fe2-88fd-0f6d88b6e92b.png)
that phase does:

1. read which nodes are registered in ProxySQL
2. Build empty objects representing the nodes (filling only the information available from Proxysql)
3. connect to all the node (in parallel) 
4. Collect the nodes status
5. close connections on each node
6. return the collection of nods object for elaboration

the code is very simple. When we have the data collection running in parallel we have a loop that wait for reconcile the collection. This loop has a timeout `CheckTimeout`, but normally the nodes returns much faster than the timeout occurs, and when all the nodes are back the execution of the loop is interrupted. 
The last Operation on the nodes before they come back and are counted as "done" is to close the connection. 
The total time taken by the nodes (each one) to connect and get all the info is `Phase: Get info for node` of which `Phase: node_connection_dbX:` is a subset.
 
Now checking the log closing connection takes nothing as expected but we still have large `data_cluster_init` time.
Let me add some more debugging information to see if we can pinpoint where the delay take place.

**Comment by Tusamarco** [comment]
@morganhowarth-fd ok I have add more information in the log to drill down what is going on.
If you can try to compile and use the latest commit in the [Issue-50](https://github.com/percona/pxc_scheduler_handler/tree/Issue-50) branch

**Comment by morganhowarth-fd** [comment]
Thanks @Tusamarco I have deployed this updated version and I'll give you the log output when we hit this issue again.

**Comment by morganhowarth-fd** [comment]
Hey @Tusamarco I've not been able to reproduce the error on 2 hosts I've deployed this `Issue-50` branch to. Other hosts that are not on the this test branch are erroring every 1 hour or so but the other hosts haven't errored since 25th Jan.

I see that the test branch is just logging entries so there's no functional change but they're based on different versions:

Server that doesn't error/timeout:
```
~# /var/lib/proxysql/pxc_scheduler_handler --version
PXC Scheduler Handler Version:  1.3.2
```

Server that errors/times out every hour or so
```
~# /var/lib/proxysql/pxc_scheduler_handler --version
PXC Scheduler Handler Version:  1.3.1
```

In 1.3.2 I see you fixed something to do with connections but that only affects ProxySQL cluster. Do you think that 1.3.2 might have any fixes for this issue we're seeing before I roll it out across our fleets?

**Comment by morganhowarth-fd** [comment]
These Datadog graphs are across the past 3 days.

This instance ending in `effa` has the new version deployed.

<img width="1540" alt="Screenshot 2022-01-27 at 09 20 17" src="https://user-images.githubusercontent.com/54585360/151329763-c1423d86-c2a3-4b42-8b4c-7f32c51bd61c.png">

The instance ending in `0142` does not have the new version deployed.

<img width="1540" alt="Screenshot 2022-01-27 at 09 20 33" src="https://user-images.githubusercontent.com/54585360/151329958-a0cfcba9-2c76-4426-9365-b0f1b16ec1ee.png">


Both instances connect to the same backend DB cluster.

**Comment by Tusamarco** [comment]
humm this is interesting. 
As said I am working to have the locking mechanism a bit more advance, so all that part will be demoted to warning. And I doubt that the changes done for the cluster may impact the area we are working on. 
But for sure I can push the changes done to have better debug to the 1.3.2 release. Those are just debug features, so may help in any case. 
let me do the QA and see.

**Comment by morganhowarth-fd** [comment]
Hey @Tusamarco - I've rolled out the `Issue-50` branch to an entire app in production which all connect to the same backend and as you can see from our Datadog logs they've not logged any errors with either "exceeded" or "lock" message since I rolled it out just after 11:00.

I'm assuming the log messages haven't changed have they as I'm searching for "lock" or "exceeded" to find any reoccurrence of the issue?

![Untitled 2](https://user-images.githubusercontent.com/54585360/151836104-29b3a6d0-7bbd-494a-93bb-a06eecb80594.png)

**Comment by morganhowarth-fd** [comment]
@Tusamarco I did get another reoccurrence from one of the instances yesterday around 23:33 UK time:

```
[INFO]:2022-01-31 15:33:07 - Go version: go1.16.13
[DEBUG]:2022-01-31 15:33:07 - Testing the log
[INFO]:2022-01-31 15:33:07 - Testing the log
[WARNING]:2022-01-31 15:33:07 - Testing the log
[ERROR]:2022-01-31 15:33:07 - testing log errors
[DEBUG]:2022-01-31 15:33:07 - Log initialized
[INFO]:2022-01-31 15:33:07 - LockerImpl initialized
[ERROR]:2022-01-31 15:33:07 - A lock file named: /tmp/10_HG_100_W_HG_101_R  already exists.
[DEBUG]:2022-01-31 15:33:09 - time taken :4262 checkTimeOut : 4000
[WARNING]:2022-01-31 15:33:09 - CheckTimeout exceeded try to increase it above the execution time : 4262
[DEBUG]:2022-01-31 15:33:09 - waitingGroup composed by [after loop]: #1
[DEBUG]:2022-01-31 15:33:09 - PXC cluster data nodes initialized
[DEBUG]:2022-01-31 15:33:09 - Evaluating node 100_geocomply-db-3.usva2.prod.aw.fdbox.net:3306
[DEBUG]:2022-01-31 15:33:09 - Evaluating node 101_geocomply-db-3.usva2.prod.aw.fdbox.net:3306
[DEBUG]:2022-01-31 15:33:09 - Evaluating node 101_geocomply-db-2.usva2.prod.aw.fdbox.net:3306
[DEBUG]:2022-01-31 15:33:09 - Evaluating node 101_geocomply-db-1.usva2.prod.aw.fdbox.net:3306
[INFO]:2022-01-31 15:33:09 - Processing action node list and build SQL commands
[INFO]:2022-01-31 15:33:09 - Connection close
[INFO]:2022-01-31 15:33:09 - ======== Reporting execution times (nanosec/ms)by phase ============
[INFO]:2022-01-31 15:33:09 - Phase: main = 4,268,003,787 us 4268 ms
[INFO]:2022-01-31 15:33:09 - Phase: proxysql_init = 1,523,858 us 1 ms
[INFO]:2022-01-31 15:33:09 - Phase: main_connection = 495,729 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: data_cluster_init = 4,266,109,114 us 4266 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get_Parametes_from_ProxySQL = 16,006 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: loadNodes = 2,722,330 us 2 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get_Nodes_Info = 4,263,045,240 us 4263 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get info for node geocomply-db-3.usva2.prod.aw.fdbox.net:3306 = 3,187,256 us 3 ms
[INFO]:2022-01-31 15:33:09 - Phase: node_connection_geocomply-db-3.usva2.prod.aw.fdbox.net:3306 = 1,064,935 us 1 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get info for node geocomply-db-1.usva2.prod.aw.fdbox.net:3306 = 3,683,428 us 3 ms
[INFO]:2022-01-31 15:33:09 - Phase: node_connection_geocomply-db-1.usva2.prod.aw.fdbox.net:3306 = 1,272,824 us 1 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get info for node geocomply-db-2.usva2.prod.aw.fdbox.net:3306 = 3,656,369 us 3 ms
[INFO]:2022-01-31 15:33:09 - Phase: node_connection_geocomply-db-2.usva2.prod.aw.fdbox.net:3306 = 1,290,685 us 1 ms
[INFO]:2022-01-31 15:33:09 - Phase: Closing connection for node geocomply-db-3.usva2.prod.aw.fdbox.net:3306 = 44,263 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: Closing connection for node geocomply-db-1.usva2.prod.aw.fdbox.net:3306 = 40,504 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: Closing connection for node geocomply-db-2.usva2.prod.aw.fdbox.net:3306 = 32,488 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get Action Map (DataClusterImpl) = 238,499 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: Process changes - ActionMap - (ProxysqlNode) = 4,054 us 0 ms
[INFO]:2022-01-31 15:33:09
```

**Comment by Tusamarco** [comment]
@morganhowarth-fd 
can u post a bit more log BEFORE the start at `[INFO]:2022-01-31 15:33:07 - Go version: go1.16.13` ?
I think we are narrowing down the issue.

**Comment by morganhowarth-fd** [comment]
Hey @Tusamarco, here's a bit more of the log, before and after the timeout exceeds.

```
[INFO]:2022-01-31 15:33:01 - Go version: go1.16.13
[DEBUG]:2022-01-31 15:33:01 - Testing the log
[INFO]:2022-01-31 15:33:01 - Testing the log
[WARNING]:2022-01-31 15:33:01 - Testing the log
[ERROR]:2022-01-31 15:33:01 - testing log errors
[DEBUG]:2022-01-31 15:33:01 - Log initialized
[INFO]:2022-01-31 15:33:01 - LockerImpl initialized
[DEBUG]:2022-01-31 15:33:01 - ProxySQL node initialized
[DEBUG]:2022-01-31 15:33:01 - Cluster arguments  clusterid=10 hg_w:100 hg_r:101 bckhg_w:8100 bckhg_w:8101 singlePrimary:true num_writers:1 writer_is_also_r:1 retry_up:0 retry_down:2 check_timeout:4000 main_segment:0
[DEBUG]:2022-01-31 15:33:01 - Retrieving information from node: db-3:3306
[DEBUG]:2022-01-31 15:33:01 - Retrieving information from node: db-2:3306
[DEBUG]:2022-01-31 15:33:01 - Retrieving information from node: db-1:3306
[DEBUG]:2022-01-31 15:33:01 - waitingGroup composed by : #3 nodes
[DEBUG]:2022-01-31 15:33:01 - node db-2:3306 done
[DEBUG]:2022-01-31 15:33:01 - waitingGroup decreased by node db-2:3306: , now contains #2
[DEBUG]:2022-01-31 15:33:01 - node db-1:3306 done
[DEBUG]:2022-01-31 15:33:01 - waitingGroup decreased by node db-1:3306: , now contains #1
[DEBUG]:2022-01-31 15:33:01 - node db-3:3306 done
[DEBUG]:2022-01-31 15:33:01 - waitingGroup decreased by node db-3:3306: , now contains #0
[DEBUG]:2022-01-31 15:33:01 - time taken :4 checkTimeOut : 4000
[DEBUG]:2022-01-31 15:33:01 - PXC cluster data nodes initialized
[DEBUG]:2022-01-31 15:33:01 - Evaluating node 101_db-2:3306
[DEBUG]:2022-01-31 15:33:01 - Evaluating node 101_db-1:3306
[DEBUG]:2022-01-31 15:33:01 - Evaluating node 100_db-3:3306
[DEBUG]:2022-01-31 15:33:01 - Evaluating node 101_db-3:3306
[INFO]:2022-01-31 15:33:01 - Processing action node list and build SQL commands
[INFO]:2022-01-31 15:33:01 - Connection close
[INFO]:2022-01-31 15:33:01 - ======== Reporting execution times (nanosec/ms)by phase ============
[INFO]:2022-01-31 15:33:01 - Phase: main = 9,154,710 us 9 ms
[INFO]:2022-01-31 15:33:01 - Phase: proxysql_init = 1,499,313 us 1 ms
[INFO]:2022-01-31 15:33:01 - Phase: main_connection = 470,341 us 0 ms
[INFO]:2022-01-31 15:33:01 - Phase: data_cluster_init = 7,339,304 us 7 ms
[INFO]:2022-01-31 15:33:01 - Phase: Get_Parametes_from_ProxySQL = 19,382 us 0 ms
[INFO]:2022-01-31 15:33:01 - Phase: loadNodes = 2,683,593 us 2 ms
[INFO]:2022-01-31 15:33:01 - Phase: Get_Nodes_Info = 4,343,175 us 4 ms
[INFO]:2022-01-31 15:33:01 - Phase: Get info for node db-1:3306 = 3,693,299 us 3 ms
[INFO]:2022-01-31 15:33:01 - Phase: node_connection_db-1:3306 = 1,320,899 us 1 ms
[INFO]:2022-01-31 15:33:01 - Phase: Get info for node db-3:3306 = 4,154,104 us 4 ms
[INFO]:2022-01-31 15:33:01 - Phase: node_connection_db-3:3306 = 1,310,096 us 1 ms
[INFO]:2022-01-31 15:33:01 - Phase: Get info for node db-2:3306 = 3,406,880 us 3 ms
[INFO]:2022-01-31 15:33:01 - Phase: node_connection_db-2:3306 = 1,074,967 us 1 ms
[INFO]:2022-01-31 15:33:01 - Phase: Closing connection for node db-2:3306 = 38,142 us 0 ms
[INFO]:2022-01-31 15:33:01 - Phase: Closing connection for node db-1:3306 = 76,842 us 0 ms
[INFO]:2022-01-31 15:33:01 - Phase: Closing connection for node db-3:3306 = 79,920 us 0 ms
[INFO]:2022-01-31 15:33:01 - Phase: Get Action Map (DataClusterImpl) = 246,895 us 0 ms
[INFO]:2022-01-31 15:33:01 - Phase: Process changes - ActionMap - (ProxysqlNode) = 4,712 us 0 ms
[INFO]:2022-01-31 15:33:01
[INFO]:2022-01-31 15:33:03 - Go version: go1.16.13
[DEBUG]:2022-01-31 15:33:03 - Testing the log
[INFO]:2022-01-31 15:33:03 - Testing the log
[WARNING]:2022-01-31 15:33:03 - Testing the log
[ERROR]:2022-01-31 15:33:03 - testing log errors
[DEBUG]:2022-01-31 15:33:03 - Log initialized
[INFO]:2022-01-31 15:33:03 - LockerImpl initialized
[DEBUG]:2022-01-31 15:33:03 - ProxySQL node initialized
[DEBUG]:2022-01-31 15:33:03 - Cluster arguments  clusterid=10 hg_w:100 hg_r:101 bckhg_w:8100 bckhg_w:8101 singlePrimary:true num_writers:1 writer_is_also_r:1 retry_up:0 retry_down:2 check_timeout:4000 main_segment:0
[DEBUG]:2022-01-31 15:33:03 - Retrieving information from node: db-3:3306
[DEBUG]:2022-01-31 15:33:03 - Retrieving information from node: db-2:3306
[DEBUG]:2022-01-31 15:33:03 - Retrieving information from node: db-1:3306
[DEBUG]:2022-01-31 15:33:03 - waitingGroup composed by : #3 nodes
[DEBUG]:2022-01-31 15:33:03 - node db-2:3306 done
[DEBUG]:2022-01-31 15:33:03 - waitingGroup decreased by node db-2:3306: , now contains #2
[DEBUG]:2022-01-31 15:33:03 - node db-1:3306 done
[DEBUG]:2022-01-31 15:33:03 - waitingGroup decreased by node db-1:3306: , now contains #1
[DEBUG]:2022-01-31 15:33:03 - node db-3:3306 done
[DEBUG]:2022-01-31 15:33:03 - waitingGroup decreased by node db-3:3306: , now contains #0
[DEBUG]:2022-01-31 15:33:03 - time taken :7 checkTimeOut : 4000
[DEBUG]:2022-01-31 15:33:03 - PXC cluster data nodes initialized
[DEBUG]:2022-01-31 15:33:03 - Evaluating node 101_db-1:3306
[DEBUG]:2022-01-31 15:33:03 - Evaluating node 101_db-3:3306
[DEBUG]:2022-01-31 15:33:03 - Evaluating node 100_db-3:3306
[DEBUG]:2022-01-31 15:33:03 - Evaluating node 101_db-2:3306
[INFO]:2022-01-31 15:33:03 - Processing action node list and build SQL commands
[INFO]:2022-01-31 15:33:03 - Connection close
[INFO]:2022-01-31 15:33:03 - ======== Reporting execution times (nanosec/ms)by phase ============
[INFO]:2022-01-31 15:33:03 - Phase: main = 12,664,573 us 12 ms
[INFO]:2022-01-31 15:33:03 - Phase: proxysql_init = 1,716,055 us 1 ms
[INFO]:2022-01-31 15:33:03 - Phase: main_connection = 601,201 us 0 ms
[INFO]:2022-01-31 15:33:03 - Phase: data_cluster_init = 10,606,854 us 10 ms
[INFO]:2022-01-31 15:33:03 - Phase: Get_Parametes_from_ProxySQL = 29,016 us 0 ms
[INFO]:2022-01-31 15:33:03 - Phase: loadNodes = 2,856,197 us 2 ms
[INFO]:2022-01-31 15:33:03 - Phase: Get_Nodes_Info = 7,420,233 us 7 ms
[INFO]:2022-01-31 15:33:03 - Phase: Get info for node db-1:3306 = 6,227,160 us 6 ms
[INFO]:2022-01-31 15:33:03 - Phase: node_connection_db-1:3306 = 3,490,109 us 3 ms
[INFO]:2022-01-31 15:33:03 - Phase: Get info for node db-3:3306 = 6,261,617 us 6 ms
[INFO]:2022-01-31 15:33:03 - Phase: node_connection_db-3:3306 = 3,433,677 us 3 ms
[INFO]:2022-01-31 15:33:03 - Phase: Get info for node db-2:3306 = 5,555,003 us 5 ms
[INFO]:2022-01-31 15:33:03 - Phase: node_connection_db-2:3306 = 3,352,459 us 3 ms
[INFO]:2022-01-31 15:33:03 - Phase: Closing connection for node db-2:3306 = 42,850 us 0 ms
[INFO]:2022-01-31 15:33:03 - Phase: Closing connection for node db-1:3306 = 28,905 us 0 ms
[INFO]:2022-01-31 15:33:03 - Phase: Closing connection for node db-3:3306 = 20,046 us 0 ms
[INFO]:2022-01-31 15:33:03 - Phase: Get Action Map (DataClusterImpl) = 237,424 us 0 ms
[INFO]:2022-01-31 15:33:03 - Phase: Process changes - ActionMap - (ProxysqlNode) = 4,018 us 0 ms
[INFO]:2022-01-31 15:33:03
[INFO]:2022-01-31 15:33:05 - Go version: go1.16.13
[DEBUG]:2022-01-31 15:33:05 - Testing the log
[INFO]:2022-01-31 15:33:05 - Testing the log
[WARNING]:2022-01-31 15:33:05 - Testing the log
[ERROR]:2022-01-31 15:33:05 - testing log errors
[DEBUG]:2022-01-31 15:33:05 - Log initialized
[INFO]:2022-01-31 15:33:05 - LockerImpl initialized
[DEBUG]:2022-01-31 15:33:05 - ProxySQL node initialized
[DEBUG]:2022-01-31 15:33:05 - Cluster arguments  clusterid=10 hg_w:100 hg_r:101 bckhg_w:8100 bckhg_w:8101 singlePrimary:true num_writers:1 writer_is_also_r:1 retry_up:0 retry_down:2 check_timeout:4000 main_segment:0
[DEBUG]:2022-01-31 15:33:05 - Retrieving information from node: db-2:3306
[DEBUG]:2022-01-31 15:33:05 - Retrieving information from node: db-1:3306
[DEBUG]:2022-01-31 15:33:05 - Retrieving information from node: db-3:3306
[DEBUG]:2022-01-31 15:33:05 - waitingGroup composed by : #3 nodes
[DEBUG]:2022-01-31 15:33:05 - node db-3:3306 done
[DEBUG]:2022-01-31 15:33:05 - waitingGroup decreased by node db-3:3306: , now contains #2
[DEBUG]:2022-01-31 15:33:05 - node db-1:3306 done
[DEBUG]:2022-01-31 15:33:05 - node db-2:3306 done
[DEBUG]:2022-01-31 15:33:05 - waitingGroup decreased by node db-2:3306: , now contains #1
[DEBUG]:2022-01-31 15:33:05 - waitingGroup decreased by node db-1:3306: , now contains #1
[INFO]:2022-01-31 15:33:07 - Go version: go1.16.13
[DEBUG]:2022-01-31 15:33:07 - Testing the log
[INFO]:2022-01-31 15:33:07 - Testing the log
[WARNING]:2022-01-31 15:33:07 - Testing the log
[ERROR]:2022-01-31 15:33:07 - testing log errors
[DEBUG]:2022-01-31 15:33:07 - Log initialized
[INFO]:2022-01-31 15:33:07 - LockerImpl initialized
[ERROR]:2022-01-31 15:33:07 - A lock file named: /tmp/10_HG_100_W_HG_101_R  already exists.
[DEBUG]:2022-01-31 15:33:09 - time taken :4262 checkTimeOut : 4000
[WARNING]:2022-01-31 15:33:09 - CheckTimeout exceeded try to increase it above the execution time : 4262
[DEBUG]:2022-01-31 15:33:09 - waitingGroup composed by [after loop]: #1
[DEBUG]:2022-01-31 15:33:09 - PXC cluster data nodes initialized
[DEBUG]:2022-01-31 15:33:09 - Evaluating node 100_db-3:3306
[DEBUG]:2022-01-31 15:33:09 - Evaluating node 101_db-3:3306
[DEBUG]:2022-01-31 15:33:09 - Evaluating node 101_db-2:3306
[DEBUG]:2022-01-31 15:33:09 - Evaluating node 101_db-1:3306
[INFO]:2022-01-31 15:33:09 - Processing action node list and build SQL commands
[INFO]:2022-01-31 15:33:09 - Connection close
[INFO]:2022-01-31 15:33:09 - ======== Reporting execution times (nanosec/ms)by phase ============
[INFO]:2022-01-31 15:33:09 - Phase: main = 4,268,003,787 us 4268 ms
[INFO]:2022-01-31 15:33:09 - Phase: proxysql_init = 1,523,858 us 1 ms
[INFO]:2022-01-31 15:33:09 - Phase: main_connection = 495,729 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: data_cluster_init = 4,266,109,114 us 4266 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get_Parametes_from_ProxySQL = 16,006 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: loadNodes = 2,722,330 us 2 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get_Nodes_Info = 4,263,045,240 us 4263 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get info for node db-3:3306 = 3,187,256 us 3 ms
[INFO]:2022-01-31 15:33:09 - Phase: node_connection_db-3:3306 = 1,064,935 us 1 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get info for node db-1:3306 = 3,683,428 us 3 ms
[INFO]:2022-01-31 15:33:09 - Phase: node_connection_db-1:3306 = 1,272,824 us 1 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get info for node db-2:3306 = 3,656,369 us 3 ms
[INFO]:2022-01-31 15:33:09 - Phase: node_connection_db-2:3306 = 1,290,685 us 1 ms
[INFO]:2022-01-31 15:33:09 - Phase: Closing connection for node db-3:3306 = 44,263 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: Closing connection for node db-1:3306 = 40,504 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: Closing connection for node db-2:3306 = 32,488 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get Action Map (DataClusterImpl) = 238,499 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: Process changes - ActionMap - (ProxysqlNode) = 4,054 us 0 ms
[INFO]:2022-01-31 15:33:09
[INFO]:2022-01-31 15:33:09 - Go version: go1.16.13
[DEBUG]:2022-01-31 15:33:09 - Testing the log
[INFO]:2022-01-31 15:33:09 - Testing the log
[WARNING]:2022-01-31 15:33:09 - Testing the log
[ERROR]:2022-01-31 15:33:09 - testing log errors
[DEBUG]:2022-01-31 15:33:09 - Log initialized
[INFO]:2022-01-31 15:33:09 - LockerImpl initialized
[DEBUG]:2022-01-31 15:33:09 - ProxySQL node initialized
[DEBUG]:2022-01-31 15:33:09 - Cluster arguments  clusterid=10 hg_w:100 hg_r:101 bckhg_w:8100 bckhg_w:8101 singlePrimary:true num_writers:1 writer_is_also_r:1 retry_up:0 retry_down:2 check_timeout:4000 main_segment:0
[DEBUG]:2022-01-31 15:33:09 - Retrieving information from node: db-3:3306
[DEBUG]:2022-01-31 15:33:09 - Retrieving information from node: db-2:3306
[DEBUG]:2022-01-31 15:33:09 - Retrieving information from node: db-1:3306
[DEBUG]:2022-01-31 15:33:09 - waitingGroup composed by : #3 nodes
[DEBUG]:2022-01-31 15:33:09 - node db-3:3306 done
[DEBUG]:2022-01-31 15:33:09 - waitingGroup decreased by node db-3:3306: , now contains #2
[DEBUG]:2022-01-31 15:33:09 - node db-2:3306 done
[DEBUG]:2022-01-31 15:33:09 - waitingGroup decreased by node db-2:3306: , now contains #1
[DEBUG]:2022-01-31 15:33:09 - node db-1:3306 done
[DEBUG]:2022-01-31 15:33:09 - waitingGroup decreased by node db-1:3306: , now contains #0
[DEBUG]:2022-01-31 15:33:09 - time taken :5 checkTimeOut : 4000
[DEBUG]:2022-01-31 15:33:09 - PXC cluster data nodes initialized
[DEBUG]:2022-01-31 15:33:09 - Evaluating node 100_db-3:3306
[DEBUG]:2022-01-31 15:33:09 - Evaluating node 101_db-3:3306
[DEBUG]:2022-01-31 15:33:09 - Evaluating node 101_db-2:3306
[DEBUG]:2022-01-31 15:33:09 - Evaluating node 101_db-1:3306
[INFO]:2022-01-31 15:33:09 - Processing action node list and build SQL commands
[INFO]:2022-01-31 15:33:09 - Connection close
[INFO]:2022-01-31 15:33:09 - ======== Reporting execution times (nanosec/ms)by phase ============
[INFO]:2022-01-31 15:33:09 - Phase: main = 10,232,527 us 10 ms
[INFO]:2022-01-31 15:33:09 - Phase: proxysql_init = 1,106,129 us 1 ms
[INFO]:2022-01-31 15:33:09 - Phase: main_connection = 583,548 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: data_cluster_init = 8,775,933 us 8 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get_Parametes_from_ProxySQL = 19,736 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: loadNodes = 3,062,621 us 3 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get_Nodes_Info = 5,393,351 us 5 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get info for node db-2:3306 = 4,166,358 us 4 ms
[INFO]:2022-01-31 15:33:09 - Phase: node_connection_db-2:3306 = 1,396,274 us 1 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get info for node db-1:3306 = 4,162,969 us 4 ms
[INFO]:2022-01-31 15:33:09 - Phase: node_connection_db-1:3306 = 1,480,529 us 1 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get info for node db-3:3306 = 3,402,975 us 3 ms
[INFO]:2022-01-31 15:33:09 - Phase: node_connection_db-3:3306 = 1,096,114 us 1 ms
[INFO]:2022-01-31 15:33:09 - Phase: Closing connection for node db-3:3306 = 42,009 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: Closing connection for node db-2:3306 = 36,689 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: Closing connection for node db-1:3306 = 32,496 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: Get Action Map (DataClusterImpl) = 242,183 us 0 ms
[INFO]:2022-01-31 15:33:09 - Phase: Process changes - ActionMap - (ProxysqlNode) = 4,508 us 0 ms
[INFO]:2022-01-31 15:33:09
[INFO]:2022-01-31 15:33:11 - Go version: go1.16.13
[DEBUG]:2022-01-31 15:33:11 - Testing the log
[INFO]:2022-01-31 15:33:11 - Testing the log
[WARNING]:2022-01-31 15:33:11 - Testing the log
[ERROR]:2022-01-31 15:33:11 - testing log errors
[DEBUG]:2022-01-31 15:33:11 - Log initialized
[INFO]:2022-01-31 15:33:11 - LockerImpl initialized
[DEBUG]:2022-01-31 15:33:11 - ProxySQL node initialized
[DEBUG]:2022-01-31 15:33:11 - Cluster arguments  clusterid=10 hg_w:100 hg_r:101 bckhg_w:8100 bckhg_w:8101 singlePrimary:true num_writers:1 writer_is_also_r:1 retry_up:0 retry_down:2 check_timeout:4000 main_segment:0
[DEBUG]:2022-01-31 15:33:11 - Retrieving information from node: db-3:3306
[DEBUG]:2022-01-31 15:33:11 - Retrieving information from node: db-2:3306
[DEBUG]:2022-01-31 15:33:11 - Retrieving information from node: db-1:3306
[DEBUG]:2022-01-31 15:33:11 - waitingGroup composed by : #3 nodes
[DEBUG]:2022-01-31 15:33:11 - node db-2:3306 done
[DEBUG]:2022-01-31 15:33:11 - waitingGroup decreased by node db-2:3306: , now contains #2
[DEBUG]:2022-01-31 15:33:11 - node db-1:3306 done
[DEBUG]:2022-01-31 15:33:11 - waitingGroup decreased by node db-1:3306: , now contains #1
[DEBUG]:2022-01-31 15:33:11 - node db-3:3306 done
[DEBUG]:2022-01-31 15:33:11 - waitingGroup decreased by node db-3:3306: , now contains #0
[DEBUG]:2022-01-31 15:33:11 - time taken :5 checkTimeOut : 4000
[DEBUG]:2022-01-31 15:33:11 - PXC cluster data nodes initialized
[DEBUG]:2022-01-31 15:33:11 - Evaluating node 101_db-3:3306
[DEBUG]:2022-01-31 15:33:11 - Evaluating node 101_db-2:3306
[DEBUG]:2022-01-31 15:33:11 - Evaluating node 101_db-1:3306
[DEBUG]:2022-01-31 15:33:11 - Evaluating node 100_db-3:3306
[INFO]:2022-01-31 15:33:11 - Processing action node list and build SQL commands
[INFO]:2022-01-31 15:33:11 - Connection close
[INFO]:2022-01-31 15:33:11 - ======== Reporting execution times (nanosec/ms)by phase ============
[INFO]:2022-01-31 15:33:11 - Phase: main = 10,703,285 us 10 ms
[INFO]:2022-01-31 15:33:11 - Phase: proxysql_init = 1,675,131 us 1 ms
[INFO]:2022-01-31 15:33:11 - Phase: main_connection = 566,352 us 0 ms
[INFO]:2022-01-31 15:33:11 - Phase: data_cluster_init = 8,650,468 us 8 ms
[INFO]:2022-01-31 15:33:11 - Phase: Get_Parametes_from_ProxySQL = 18,820 us 0 ms
[INFO]:2022-01-31 15:33:11 - Phase: loadNodes = 2,865,428 us 2 ms
[INFO]:2022-01-31 15:33:11 - Phase: Get_Nodes_Info = 5,474,443 us 5 ms
[INFO]:2022-01-31 15:33:11 - Phase: Get info for node db-1:3306 = 4,075,942 us 4 ms
[INFO]:2022-01-31 15:33:11 - Phase: node_connection_db-1:3306 = 1,323,133 us 1 ms
[INFO]:2022-01-31 15:33:11 - Phase: Get info for node db-2:3306 = 3,448,555 us 3 ms
[INFO]:2022-01-31 15:33:11 - Phase: node_connection_db-2:3306 = 1,220,380 us 1 ms
[INFO]:2022-01-31 15:33:11 - Phase: Get info for node db-3:3306 = 4,181,803 us 4 ms
[INFO]:2022-01-31 15:33:11 - Phase: node_connection_db-3:3306 = 1,259,265 us 1 ms
[INFO]:2022-01-31 15:33:11 - Phase: Closing connection for node db-2:3306 = 47,051 us 0 ms
[INFO]:2022-01-31 15:33:11 - Phase: Closing connection for node db-1:3306 = 51,375 us 0 ms
[INFO]:2022-01-31 15:33:11 - Phase: Closing connection for node db-3:3306 = 29,745 us 0 ms
[INFO]:2022-01-31 15:33:11 - Phase: Get Action Map (DataClusterImpl) = 270,606 us 0 ms
[INFO]:2022-01-31 15:33:11 - Phase: Process changes - ActionMap - (ProxysqlNode) = 4,736 us 0 ms
[INFO]:2022-01-31 15:33:11
```

**Comment by Tusamarco** [comment]
exactly @morganhowarth-fd  can u please post the log with cuts? so I can read all. 
I think we are getting there.

**Comment by Tusamarco** [comment]
@morganhowarth-fd ok here we go, this latest [commit](https://github.com/percona/pxc_scheduler_handler/commit/cf4cc14b84af5f3d52a2f7e9684c14689d299dd1) should resolve the issue.
Checking the log you shared with the execution chain, it could be that in some conditions we have a contention in the object that keep track of the threads still in execution. That will prevent a correct decrement of the counter and conclusion of the cycle. 
I have add a mutex on the methods that are involved in the cycle and hope this will solve the issue.
Please test and let me know, I have done some QA but do not have the level of traffic you generate, and this is a condition that shows up only on high contention.

**Comment by morganhowarth-fd** [comment]
@Tusamarco Thanks! I'll roll this out and report back!

**Comment by morganhowarth-fd** [comment]
@Tusamarco - I rolled this new version out to 3 production deployments just after 11:00 and as you can see from the Datadog logs it looks like the error has stopped! We were getting the error quite consistently but now it's no longer showing up.

I think the mutex stuff you added has resolved it.

![image](https://user-images.githubusercontent.com/54585360/152164083-b649146c-bcc0-44bd-b63f-97b3d8b68fd1.png)

**Comment by Tusamarco** [comment]
@morganhowarth-fd that is great news. Let us wait for 24hrs and see. I am doing qa and will be ready to merge and prepare 1.3.3 release soon

**Comment by morganhowarth-fd** [comment]
Hey @Tusamarco - I've checked this morning and there are no errors for instances on the new version. We do still get error for those on the previous version before the mutex stuff.

Please let me know when you release 1.3.3!

**Comment by Tusamarco** [comment]
@morganhowarth-fd release is out. 
Please always rollout on one environment for test, before doing full deployment. As said I cannot validate your case with a a QA case (yet).
thank a lot for the issue discovery and great help in identify the root cause

**Comment by Tusamarco** [comment]
@morganhowarth-fd please let me know if we can close this issue as fixed/resolved. thanks

**Comment by morganhowarth-fd** [comment]
Hey @Tusamarco I rolled out 1.3.3 to a specific production deployment and it fixed the issue.

I then rolled it out to all our production deployments and we've not had the issue being reported since.

You may close this issue now. Thanks so much for your time in helping debug the issue.
